title: Welcome to Eternal Surfer
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

include: ["_pages"]

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  
footer:
  links:
    - label: Sitemap
      url: "/sitemap.xml"  
  
