# Site settings
title: Eternal Surfer
email: 
description: >- # this means to ignore newlines
  Uncomplicate is home to articles, reviews on how to make your life simple 
  so that you get more time for your passions and loved things in life.

# theme settings  
theme: minima

include: ["_pages"]

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap  
  

permalink: /:categories/:title/

include: ["_pages"] 
  
header_pages:
  - about.markdown
  - blogs.markdown
  - archive.markdown
  - categories.markdown  

head_scripts:
  - /assets/js/back-to-top.js 
  
paginate: 2
paginate_path: "/archive/page:num/"  